Change again

diff --git a/.github/workflows/nextjs.yml b/.github/workflows/nextjs.yml
--- a/.github/workflows/nextjs.yml
+++ b/.github/workflows/nextjs.yml
@@ -26,14 +26,29 @@ jobs:
         with:
           node-version: "20"
 
+      - name: Detect package manager
+        id: detect-package-manager
+        run: |
+          if [ -f "yarn.lock" ]; then
+            echo "manager=yarn" >> $GITHUB_OUTPUT
+            echo "command=install" >> $GITHUB_OUTPUT
+            echo "runner=yarn" >> $GITHUB_OUTPUT
+          elif [ -f "package.json" ]; then
+            echo "manager=npm" >> $GITHUB_OUTPUT
+            echo "command=install" >> $GITHUB_OUTPUT
+            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
+          else
+            echo "Unable to determine package manager"
+            exit 1
+          fi
+
       - name: Install dependencies
-        run: npm install # Ensure all dependencies, including Next.js, are installed
+        run: |
+          ${{ steps.detect-package-manager.outputs.runner }} next build
+          ${{ steps.detect-package-manager.outputs.runner }} next export
 
       - name: Build with Next.js
-        run: npm run build # Run the build command
-
-      - name: Export Next.js site (if applicable)
-        run: npm run export # Run export if you're building a static site
+        run: ${{ steps.detect-package-manager.outputs.runner }} next build || true
 
       - name: Upload artifact
         uses: actions/upload-pages-artifact@v3
